services:
  - type: web
    name: tiros-user-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /(?!sitemap\.xml|robots\.txt).*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://tiros-backend.onrender.com
      - key: NODE_ENV
        value: production

